# Site metadata.

# Canonical URL
url: https://www.romariomaxwell.me/pulse

name: Pulse
title: "The pulse of the Jamaican .gov.jm space"
description: "How Jamaican government domains are meeting best practices on the web."

# Data sources. These URLs should have their content updated in-place.
data:
  # URL where we download the .gov.jm domain list from.
  domains_url: "https://raw.githubusercontent.com/macsual/dotgov-jamaica-domains/master/current.csv"

bucket: unused
